### ISSUE TITLE
all: add a .git precommit hook

### ISSUE THREAD

**Issue by odeke-em** [tendermint/coding#22]
So the Go project has a precommit hook for Git that checks if all the files are go-fmt'd at
https://github.com/golang/go/blob/964639cc338db650ccadeafb7424bc8ebb2c0f6c/misc/git/pre-commit#L1-L26

I think this could be a start for always ensuring that our source code is go-fmt'd and then later on we can add other rules and tools.

**Comment by zramsay** [comment]
this is pretty much handled by metalinter & we don't have a problem with PRs that lack fmt
