### ISSUE TITLE
Catalog seldom used or unused functions 

### ISSUE THREAD

**Issue by ebuchman** [tendermint/coding#25]
eg. IsDirEmpty (https://github.com/tendermint/tmlibs/pull/34#issuecomment-321699145)

**Comment by zramsay** [comment]
shouldn't the unused ones be removed?

**Comment by ebuchman** [comment]
Yes possibly, or else linked to issues about code is supposed to exist to use them

**Comment by rigelrozanski** [comment]
checkout this https://github.com/remyoudompheng/go-misc/tree/master/deadcode

**Comment by zramsay** [comment]
linters that address this are widely applied across the stack
