### ISSUE TITLE
automate pushing docker images on release

### ISSUE THREAD

**Issue by zramsay** [tendermint/coding#32]
- see this comment https://github.com/tendermint/tendermint/issues/678#issuecomment-331975922

- applied also to ethermint, and ... ?

**Comment by melekes** [comment]
Tendermint: https://github.com/tendermint/tendermint/pull/684

note for other projects I would recommend first to try https://github.com/goreleaser/goreleaser

**Comment by adrianbrink** [comment]
Ethermint: https://github.com/tendermint/ethermint/issues/316

It would be great to also extend it to work with docker.

**Comment by melekes** [comment]
goreleaser can build and push docker images

**Comment by adrianbrink** [comment]
Sweet. Then I'll try and use it on ethermint
