### ISSUE TITLE
Add a scripts folder

### ISSUE THREAD

**Issue by rigelrozanski** [tendermint/coding#6]
Test_coverage.sh is a script, not really a description file.. we should think about how to reorg. this repo and possibly export some of these docs to other repos

**Comment by adrianbrink** [comment]
I think so. Check out ethermint, it has a scripts folder.

**Comment by zramsay** [comment]
Agree. we should have a scripts folder that has useful snippets one can easily run to setup X or (something that ties in >1 repo)
