### ISSUE TITLE
project shelldown

### ISSUE THREAD

**Issue by zramsay** [tendermint/coding#9]
**Purpose:** ensure all docs / tutorials / guides / explainers / hello-world examples are tested.

I plan to begin this once the docs have advanced a bunch more and the repos are a bit more organized, probably around the end of the month.

**Comment by rigelrozanski** [comment]
Awesome, totally happy to help out on this one

**Comment by zramsay** [comment]
bash begone

**Comment by rigelrozanski** [comment]
I'm with you here... I still think the concept of shelldown could be useful to test the tutorial CLI... doesn't need to be with bash, could actually be right with go-command line testing, but still need some kind of shelldown interface.. I'll think about this more... If you get that work done on the go-command CLI testing for tendermint I could port that to shelldown
